concourse-db:
  image: postgres:9.5
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: leanswpass
    PGDATA: /database

concourse-web:
  image: concourse/concourse:2.4.0
  labels:
    io.rancher.container.hostname_override: container_name
  links: [concourse-db]
  command: web
  ports: ["8080:8080"]
  volumes: ["/var/keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: concourse
    CONCOURSE_BASIC_AUTH_PASSWORD: leanswpass
    CONCOURSE_EXTERNAL_URL: "http://${CONCOURSE_EXTERNAL_ADDR}:8080"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:leanswpass@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse:2.4.0
  privileged: true
  labels:
    io.rancher.container.hostname_override: container_name
  links: [concourse-web]
  command: worker
  volumes: ["/var/keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

