jenkins-datavolume:
  image: alpine
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /var/jenkins_home
  command: echo "Create Jenkins volume."

jenkins-web:
  image: registry.alauda.cn/fanlin/jenkins-v2-all-in-one:2.19.2
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: jenkins-datavolume
  ports: ["8080:8080"]
  privileged: true
  volumes_from:
    - jenkins-datavolume
  environment:
    JAVA_OPTS: "-Duser.timezone=Asia/Shanghai -Djenkins.install.runSetupWizard=false" 
