.catalog:
  name: "Jenkins v2"
  version: "2.19.2"
  description: "Deploy Jenkins v2 In Rancher"
  uuid: jenkins-v2-0
  minimum_rancher_version: v1.0.0
      
jenkins-web:
  scale: 1
jenkins-datavolume:
  scale: 1
